apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: u9o2fd2ms-go-gitops
  description: This is GitOps manifest for u9o2fd2ms-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: u9o2fd2ms-go
    janus-idp.io/tekton: u9o2fd2ms-go
    backstage.io/kubernetes-id: u9o2fd2ms-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:u9o2fd2ms-go
