apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u9o2fd2ms-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:8cf87a5b757ed70a652716b3d05ac9801e2c0e5a@sha256:47c60faa7f071de7ce213b8aa582f4e045a984becffa36edaae7916afe6e3f9a
          name: container-image
